### ISSUE TITLE
Unable to open object (object 'RD' doesn't exist)"

### ISSUE THREAD

**Issue by AmazingSAR** [isce-framework/isce3#21]
When testing [NISAR Sample Data Product](https://nisar.asf.earthdatacloud.nasa.gov/NISAR-SAMPLE-DATA/L0B/ALOS1_Rosamond_20081012/NISAR_L0_PR_RRSD_001_005_A_128S_20081012T060910_20081012T060926_P01101_F_J_001.h5) with ISCE3, **KeyError** occurred in "~/isce3/packages/nisar/products/readers/Raw/Raw.py" line 603.
```
Exception has occurred: KeyError
"Unable to open object (object 'RD' doesn't exist)"
  File "/home/amazingsar/install/isce3.3/packages/nisar/products/readers/Raw/Raw.py", line 603, in getRdWdWl
    return (fid[path_txrx]["RD"][()], fid[path_txrx]["WD"][()],
  File "/home/amazingsar/install/isce3.3/packages/nisar/antenna/pattern.py", line 289, in __init__
    rd_all[pol], wd_all[pol], wl_all[pol] = raw.getRdWdWl(
  File "/home/amazingsar/install/isce3/packages/nisar/workflows/focus.py", line 1505, in focus
    antpat = AntennaPattern(raw, dem, antparser,
  File "/home/amazingsar/install/isce3/packages/nisar/workflows/focus.py", line 1609, in main
    focus(cfg, args.run_config_path)
  File "/home/amazingsar/install/isce3/packages/nisar/workflows/focus.py", line 1613, in <module>
    main(sys.argv[1:])
KeyError: "Unable to open object (object 'RD' doesn't exist)"
```

Here is my **rslc_config.yaml**.

<details>

```
runconfig:
    groups:
        input_file_group:
            input_file_path:
            -   NISAR_L0_PR_RRSD_001_005_A_128S_20081012T060910_20081012T060926_P01101_F_J_001.h5
            qa_input_file: ./slc.h5
        dynamic_ancillary_file_group:
            dem_file:
            dem_file_description:
            orbit:
            pointing:
            external_calibration:
            internal_calibration: REE_INSTRUMENT_TABLE.h5
            antenna_pattern: REE_ANTPAT_CUTS_DATA.h5
            corner_reflector_file:
        product_path_group:
            product_path: /out
            scratch_path: .
            sas_output_file: ./rslc.h5
            sas_config_file: ./rslc_config.yaml
            qa_output_dir: ./qa
        primary_executable:
            product_type: RSLC
            product_version: 0.1.0
            processing_type: CUSTOM
            mission_id:
            processing_center: JPL
            partial_granule_id: None
        geometry:
            relative_orbit_number: 1
            frame_number: 1
        worker:
            gpu_enabled: false
            gpu_id: 0
        processing:
            output_grid:
                start_time:
                end_time:
                start_range:
                end_range:
                output_prf:
                time_snap_interval: 1.0
            ephemeris_crop_pad: 10.0
            range_window:
                kind: Kaiser
                shape: 1.6
            azimuth_window:
                kind: Kaiser
                shape: 0.0
            radio_frequency_interference:
                detection_enabled: true
                mitigation_enabled: false
                mitigation_algorithm: ST-EVD
                cpi_length: 32
                num_range_blocks: 1
                max_emitters: 16
                num_max_trim: 0
                num_min_trim: 0
                max_num_rfi_ev: 2
                num_cpi_per_threshold_block: 20
                threshold_hyperparameters:
                    x:
                    -   2.0
                    -   20.0
                    y:
                    -   5.0
                    -   20.0
            range_common_band_filter:
                attenuation: 40.0
                width: 0.15
            rdr2geo:
                tol_height: 1e-05
                look_min_deg: 0.0
                look_max_deg: 90.0
            geo2rdr:
                tol_aztime: 1e-07
                time_start:
                time_end:
            doppler:
                azimuth_boresight_deg: 0.0
                interp_method: bilinear
                spacing:
                    range: 2000.0
                    azimuth: 1.0
            rangecomp:
                mode: full
                block_size:
                    range: 0
                    azimuth: 1024
            azcomp:
                block_size:
                    range: 64
                    azimuth: 64
                azimuth_resolution: 6.0
                kernel:
                    type: Knab
                    halfwidth: 4
                    approx_oversample: 1.7
                    fit: Table
                    fit_order: 2048
            dry_troposphere_model: nodelay
            dem:
                reference_height: 0.0
                interp_method: biquintic
            nominal_antenna_size:
                range: 12.0
                azimuth: 12.0
            encoding_scale_factor: 1e-08
            delete_tempfiles: true
            debug_dump_height: false
            is_enabled:
                presum_blu: true
                rangecomp: true
                eap: true
                range_cor: true
                azcomp: true
        qa:
            workflows:
                validate: true
                qa_reports: true
                absolute_radiometric_calibration: true
                noise_estimation: true
                point_target_analyzer: true
            qa_reports:
                backscatter_img:
                    linear_units: true
                    nlooks_freqa:
                    nlooks_freqb:
                    longest_side_max: 2048
                    percentile_for_clipping:
                    -   5.0
                    -   95.0
                    gamma: 0.5
                    tile_shape:
                    -   1024
                    -   1024
                histogram:
                    decimation_ratio:
                    -   10
                    -   10
                    backscatter_histogram_bin_edges_range:
                    -   -80.0
                    -   20.0
                    phs_in_radians: true
                    tile_shape:
                    -   1024
                    -   -1
                range_spectra:
                    az_decimation: 8
                    hz_to_mhz: true
                    tile_height: 512
            absolute_radiometric_calibration:
                nchip: 64
                upsample_factor: 32
                peak_find_domain: time
                nfit: 5
                power_method: box
                power_threshold: 3.0
            point_target_analyzer:
                nchip: 64
                upsample_factor: 32
                peak_find_domain: time
                num_sidelobes: 10
                predict_null: true
                fs_bw_ratio: 1.2
                window_type: rect
                window_parameter: 0.0
```

</details>
 Does anyone know what happened here?

**Comment by ghost** [comment]
The error message could be better, but I'd guess that what's happening is you're processing data from ALOS that's been packed in a NISAR-like raw data format. It's trying to read SweepSAR parameters from the raw data and not finding them. To work around this issue you can disable elevation antenna pattern correction by setting `eap: false` in the runconfig, e.g.,
```yaml
runconfig:
    groups:
        processing:
            is_enabled:
                eap: false
```
