### ISSUE TITLE
Error when geocoding RIFG

### ISSUE THREAD

**Issue by bjmarfito** [isce-framework/isce3#33]
I'm getting this error when geocoding RIFG using `insar.py`. The data I used are NISAR-simulated L1 RSLC data.

```
interpolator: BilinearInterpolator
ERROR 6: IH5:::ID=360287970189644924: Dataset does not support the SetSpatialRef() method.
```

**Comment by hfattahi** [comment]
@bjmarfito can you provide more details please. Which ISCE3 version, GDAL and HDF5 version are you using and if you are running insar.py end to end ? Can you provide more lines of the log?
Also can you confirm that RIFG and RUNW looks ok and the issue is specifically in geocoding?

**Comment by bjmarfito** [comment]
Hi @hfattahi, I'm using the develop version of ISCE3. 
GDAL version: 3.10.3
HDF5 version: 1.14.6

Attached also is the logfile for your reference.

Yes, RIFG and RUNW looks fine. Attached are the wrapped, unwrapped and coherence data from RIFG and RUNW, respectively.

[log.txt](https://github.com/user-attachments/files/20516697/log.txt)
[unw_insar.pdf](https://github.com/user-attachments/files/20516699/unw_insar.pdf)
[wrapped_insar.pdf](https://github.com/user-attachments/files/20516696/wrapped_insar.pdf)
[coherence.pdf](https://github.com/user-attachments/files/20516698/coherence.pdf)

**Comment by scottstanie** [comment]
I think `Dataset does not support the SetSpatialRef` is a warning that pops up in a number of places in isce3, but doesn't seem to cause real errors (see https://github.com/opera-adt/COMPASS/issues/216#issuecomment-1915216236)

**Comment by hfattahi** [comment]
I agree with @scottstanie that the error message does not really impact geocoding, the output data or even the metadata of the output product. So you can totally ignore it. 
We have indeed had this discussion sometime last year for silencing the error message in another part of the code. @gshiroma added a flag for the metadata cube to [optionally silence this message](https://github.com/isce-framework/isce3/blob/develop/cxx/isce3/geometry/metadataCubes.cpp#L444). The results of our discussions on that PR was summarized by @gmgunter as follows. Copying part of that summary here as I think it should help to clarify the background and the reason why it is not very easy to completely avoid this error message. 


- In general, GDAL doesn't guarantee that every raster driver supports getting/setting geotransform & spatial reference metadata. Some driver formats, such as GTiff, provide a standardized way to serialize this info, whereas others, like our custom IH5 driver for HDF5 datasets, do not.
- However, when functions in isce3 write to rasters that do support this metadata, users are likely to expect that this metadata will be correctly populated. If we don't supply this info, users are likely to be surprised/disappointed when isce3-generated rasters don't load properly in QGIS, for example.
- AFAICT, GDAL doesn't expose an API that can be used to safely check whether a particular driver or dataset supports setting spatial reference or geotransform info. In addition, I'm not sure that there's any way to handle this with a try ... catch block at the C++ level, because GDAL's C++ code doesn't raise exceptions. When you try to call [SetSpatialRef()](https://gdal.org/doxygen/classGDALDataset.html#a6cebbb2fb091ebf263fea53b5f2b219e) for a dataset that doesn't support this operation, GDAL emits an error message and returns an error code. Even if we properly handle the error within isce3, the error message itself might be confusing for users.

With that we approved @gshiroma's proposed approach to make the SetGeotransform() and SetSpatialRef() steps optional based on a user-configurable flag for metadata cube. Perhaps we could do the same for GeocodeCov as well. Maybe we avoided doing that as the solution is not really complete.

Again please note that this error does not impact NISAR geocoded products at all. we have other ways to configure the geospatial information for geocoded rasters in NISAR HDF5 products.

Hope this helps to clarify.

**Comment by bjmarfito** [comment]
Thank you for your reply @hfattahi and @scottstanie.

However, the geocode product with name `_product.h5`  does not contain the geocoded wrapped and unwrapped IFG. Do I need to geocode them manually?

**Comment by hfattahi** [comment]
No you don't need to geocode manually. Would you please share your run config. Note that insar.py workflow is able to produce either of RIFG. RUNW, GUNW, ROFF, GOFF and you have to specifically ask for geocoded products. See [here for all options](https://github.com/isce-framework/isce3/blob/develop/share/nisar/schemas/insar.yaml#L72). The geocoded products are produced in a separate product (GUNW, GOFF). If you want geocoded only, set product_type to "GUNW", and if you want radar and geocoded interferograms wrapped and unwrapped set the product type to "RIFG_RUNW_GUNW".

**Comment by bjmarfito** [comment]
Hi @hfattahi, here is my run config file for your reference, please.

[insar.txt](https://github.com/user-attachments/files/20560996/insar.txt)

**Comment by hfattahi** [comment]
I see that your product_type is "GUNW". All rasters in that product should be geocoded. 
I suggest that you remove runw_path and rifg_path from geocode section, choose product_type as GUNW and try a clean run. 
Once you have a clean run, please provide more clear information such as what do you exactly see in the output folder and how the plots of unwrapped phase or coherence looks like in the GUNW file.

**Comment by bjmarfito** [comment]
Thank you for this info, @hfattahi. I edited the config file based on your comments and running `insar.py` right now. I will update you once it is done.

**Comment by bjmarfito** [comment]
Hi @hfattahi, I generated GUNW using your workflow. However, the file seems empty.


```
Dataset 'unwrappedPhase' 
                                    Size:  1x1
                                    MaxSize:  1x1
                                    Datatype:   H5T_IEEE_F32LE (single)
                                    ChunkSize:  1x1
                                    Filters:  shuffle, deflate(1)
                                    FillValue:  0.000000
                                    Attributes:
                                        'description':  'Unwrapped interferogram between HH layers'
                                        'units':  'radians'
                                        'grid_mapping':  'projection'
                                        'DIMENSION_LIST':  H5T_VLEN
                                        '_FillValue':  NaN
                                        'min_value':  NaN
                                        'mean_value':  0.000000
                                        'max_value':  NaN
                                        'sample_stddev':  0.000000
```

Here is the link folder containing the output GUNW and config file: [NISAR_simulated_data](https://entuedu.sharepoint.com/:f:/r/teams/EOS-RS2/Shared%20Documents/General/02_Shared/Bryan/[NISAR_simulated_data](https://entuedu.sharepoint.com/:f:/r/teams/EOS-RS2/Shared%20Documents/General/02_Shared/Bryan/NISAR_simulated_data?csf=1&web=1&e=nWDQ82)?csf=1&web=1&e=nWDQ82)
